package dev.doctor4t.trainmurdermystery.datagen;

import dev.doctor4t.trainmurdermystery.index.TMMBlocks;
import dev.doctor4t.trainmurdermystery.index.TMMEntities;
import dev.doctor4t.trainmurdermystery.index.TMMItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class TrainMurderMysteryLangGen extends FabricLanguageProvider {

    public TrainMurderMysteryLangGen(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder builder) {
        builder.add(TMMEntities.SEAT, "Seat");
        builder.add(TMMEntities.PLAYER_BODY, "Body");

        builder.add(TMMBlocks.STAINLESS_STEEL_VENT_SHAFT, "Stainless Steel Vent Shaft");
        builder.add(TMMBlocks.STAINLESS_STEEL_VENT_HATCH, "Stainless Steel Vent Hatch");
        builder.add(TMMBlocks.DARK_STEEL_VENT_SHAFT, "Dark Steel Vent Shaft");
        builder.add(TMMBlocks.DARK_STEEL_VENT_HATCH, "Dark Steel Vent Hatch");
        builder.add(TMMBlocks.TARNISHED_GOLD_VENT_SHAFT, "Tarnished Gold Vent Shaft");
        builder.add(TMMBlocks.TARNISHED_GOLD_VENT_HATCH, "Tarnished Gold Vent Hatch");
        builder.add(TMMBlocks.TARNISHED_GOLD, "Tarnished Gold");
        builder.add(TMMBlocks.TARNISHED_GOLD_STAIRS, "Tarnished Gold Stairs");
        builder.add(TMMBlocks.TARNISHED_GOLD_SLAB, "Tarnished Gold Slab");
        builder.add(TMMBlocks.TARNISHED_GOLD_WALL, "Tarnished Gold Wall");
        builder.add(TMMBlocks.TARNISHED_GOLD_PILLAR, "Tarnished Gold Pillar");
        builder.add(TMMBlocks.GOLD, "Gold");
        builder.add(TMMBlocks.GOLD_STAIRS, "Gold Stairs");
        builder.add(TMMBlocks.GOLD_SLAB, "Gold Slab");
        builder.add(TMMBlocks.GOLD_WALL, "Gold Wall");
        builder.add(TMMBlocks.GOLD_PILLAR, "Gold Pillar");
        builder.add(TMMBlocks.PRISTINE_GOLD, "Pristine Gold");
        builder.add(TMMBlocks.PRISTINE_GOLD_STAIRS, "Pristine Gold Stairs");
        builder.add(TMMBlocks.PRISTINE_GOLD_SLAB, "Pristine Gold Slab");
        builder.add(TMMBlocks.PRISTINE_GOLD_WALL, "Pristine Gold Wall");
        builder.add(TMMBlocks.PRISTINE_GOLD_PILLAR, "Pristine Gold Pillar");
        builder.add(TMMBlocks.METAL_SHEET, "Metal Sheet");
        builder.add(TMMBlocks.METAL_SHEET_STAIRS, "Metal Sheet Stairs");
        builder.add(TMMBlocks.METAL_SHEET_SLAB, "Metal Sheet Slab");
        builder.add(TMMBlocks.METAL_SHEET_WALL, "Metal Sheet Wall");
        builder.add(TMMBlocks.METAL_SHEET_DOOR, "Metal Sheet Door");
        builder.add(TMMBlocks.COCKPIT_DOOR, "Cockpit Door");
        builder.add(TMMBlocks.METAL_SHEET_WALKWAY, "Metal Sheet Walkway");
        builder.add(TMMBlocks.STAINLESS_STEEL_LADDER, "Stainless Steel Ladder");
        builder.add(TMMBlocks.STAINLESS_STEEL, "Stainless Steel");
        builder.add(TMMBlocks.STAINLESS_STEEL_STAIRS, "Stainless Steel Stairs");
        builder.add(TMMBlocks.STAINLESS_STEEL_SLAB, "Stainless Steel Slab");
        builder.add(TMMBlocks.STAINLESS_STEEL_WALL, "Stainless Steel Wall");
        builder.add(TMMBlocks.STAINLESS_STEEL_WALKWAY, "Stainless Steel Walkway");
        builder.add(TMMBlocks.STAINLESS_STEEL_PILLAR, "Stainless Steel Pillar");
        builder.add(TMMBlocks.STAINLESS_STEEL_BRANCH, "Stainless Steel Branch");
        builder.add(TMMBlocks.DARK_STEEL, "Dark Steel");
        builder.add(TMMBlocks.DARK_STEEL_STAIRS, "Dark Steel Stairs");
        builder.add(TMMBlocks.DARK_STEEL_SLAB, "Dark Steel Slab");
        builder.add(TMMBlocks.DARK_STEEL_WALL, "Dark Steel Wall");
        builder.add(TMMBlocks.DARK_STEEL_WALKWAY, "Dark Steel Walkway");
        builder.add(TMMBlocks.DARK_STEEL_PILLAR, "Dark Steel Pillar");
        builder.add(TMMBlocks.DARK_STEEL_BRANCH, "Dark Steel Branch");
        builder.add(TMMBlocks.RHOMBUS_GLASS, "Rhombus Glass");
        builder.add(TMMBlocks.HULL_GLASS, "Hull Glass");
        builder.add(TMMBlocks.RHOMBUS_HULL_GLASS, "Rhombus Hull Glass");
        builder.add(TMMBlocks.GOLDEN_GLASS_PANEL, "Golden Glass Panel");
        builder.add(TMMBlocks.CULLING_GLASS, "Culling Glass");
        builder.add(TMMBlocks.PRIVACY_GLASS_PANEL, "Privacy Glass");
        builder.add(TMMBlocks.MARBLE, "Marble");
        builder.add(TMMBlocks.MARBLE_STAIRS, "Marble Stairs");
        builder.add(TMMBlocks.MARBLE_SLAB, "Marble Slab");
        builder.add(TMMBlocks.MARBLE_WALL, "Marble Wall");
        builder.add(TMMBlocks.MARBLE_TILES, "Marble Tiles");
        builder.add(TMMBlocks.MARBLE_TILE_STAIRS, "Marble Tile Stairs");
        builder.add(TMMBlocks.MARBLE_TILE_SLAB, "Marble Tile Slab");
        builder.add(TMMBlocks.MARBLE_TILE_WALL, "Marble Tile Wall");
        builder.add(TMMBlocks.DARK_MARBLE, "Dark Marble");
        builder.add(TMMBlocks.DARK_MARBLE_STAIRS, "Dark Marble Stairs");
        builder.add(TMMBlocks.DARK_MARBLE_SLAB, "Dark Marble Slab");
        builder.add(TMMBlocks.DARK_MARBLE_WALL, "Dark Marble Wall");
        builder.add(TMMBlocks.MARBLE_MOSAIC, "Marble Mosaic");
        builder.add(TMMBlocks.WHITE_HULL, "White Hull");
        builder.add(TMMBlocks.WHITE_HULL_STAIRS, "White Hull Stairs");
        builder.add(TMMBlocks.WHITE_HULL_SLAB, "White Hull Slab");
        builder.add(TMMBlocks.WHITE_HULL_WALL, "White Hull Wall");
        builder.add(TMMBlocks.CULLING_WHITE_HULL, "Culling White Hull");
        builder.add(TMMBlocks.BLACK_HULL, "Black Hull");
        builder.add(TMMBlocks.BLACK_HULL_STAIRS, "Black Hull Stairs");
        builder.add(TMMBlocks.BLACK_HULL_SLAB, "Black Hull Slab");
        builder.add(TMMBlocks.BLACK_HULL_WALL, "Black Hull Wall");
        builder.add(TMMBlocks.CULLING_BLACK_HULL, "Culling Black Hull");
        builder.add(TMMBlocks.BLACK_HULL_SHEETS, "Black Hull Sheets");
        builder.add(TMMBlocks.BLACK_HULL_SHEET_STAIRS, "Black Hull Sheet Stairs");
        builder.add(TMMBlocks.BLACK_HULL_SHEET_SLAB, "Black Hull Sheet Slab");
        builder.add(TMMBlocks.BLACK_HULL_SHEET_WALL, "Black Hull Sheet Wall");
        builder.add(TMMBlocks.MAHOGANY_PLANKS, "Mahogany Planks");
        builder.add(TMMBlocks.MAHOGANY_STAIRS, "Mahogany Stairs");
        builder.add(TMMBlocks.MAHOGANY_SLAB, "Mahogany Slab");
        builder.add(TMMBlocks.SMOOTH_MAHOGANY, "Smooth Mahogany");
        builder.add(TMMBlocks.SMOOTH_MAHOGANY_STAIRS, "Smooth Mahogany Stairs");
        builder.add(TMMBlocks.SMOOTH_MAHOGANY_SLAB, "Smooth Mahogany Slab");
        builder.add(TMMBlocks.MAHOGANY_PANEL, "Mahogany Panel");
        builder.add(TMMBlocks.MAHOGANY_CABINET, "Mahogany Cabinet");
        builder.add(TMMBlocks.MAHOGANY_BOOKSHELF, "Mahogany Bookshelf");
        builder.add(TMMBlocks.MAHOGANY_HERRINGBONE, "Mahogany Herringbone");
        builder.add(TMMBlocks.MAHOGANY_HERRINGBONE_STAIRS, "Mahogany Herringbone Stairs");
        builder.add(TMMBlocks.MAHOGANY_HERRINGBONE_SLAB, "Mahogany Herringbone Slab");
        builder.add(TMMBlocks.BUBINGA_PLANKS, "Bubinga Planks");
        builder.add(TMMBlocks.BUBINGA_STAIRS, "Bubinga Stairs");
        builder.add(TMMBlocks.BUBINGA_SLAB, "Bubinga Slab");
        builder.add(TMMBlocks.BUBINGA_PANEL, "Bubinga Panel");
        builder.add(TMMBlocks.BUBINGA_CABINET, "Bubinga Cabinet");
        builder.add(TMMBlocks.BUBINGA_BOOKSHELF, "Bubinga Bookshelf");
        builder.add(TMMBlocks.BUBINGA_HERRINGBONE, "Bubinga Herringbone");
        builder.add(TMMBlocks.BUBINGA_HERRINGBONE_STAIRS, "Bubinga Herringbone Stairs");
        builder.add(TMMBlocks.BUBINGA_HERRINGBONE_SLAB, "Bubinga Herringbone Slab");
        builder.add(TMMBlocks.SMOOTH_BUBINGA, "Smooth Bubinga");
        builder.add(TMMBlocks.SMOOTH_BUBINGA_STAIRS, "Smooth Bubinga Stairs");
        builder.add(TMMBlocks.SMOOTH_BUBINGA_SLAB, "Smooth Bubinga Slab");
        builder.add(TMMBlocks.EBONY_PLANKS, "Ebony Planks");
        builder.add(TMMBlocks.EBONY_STAIRS, "Ebony Stairs");
        builder.add(TMMBlocks.EBONY_SLAB, "Ebony Slab");
        builder.add(TMMBlocks.EBONY_HERRINGBONE, "Ebony Herringbone");
        builder.add(TMMBlocks.EBONY_HERRINGBONE_STAIRS, "Ebony Herringbone Stairs");
        builder.add(TMMBlocks.EBONY_HERRINGBONE_SLAB, "Ebony Herringbone Slab");
        builder.add(TMMBlocks.SMOOTH_EBONY, "Smooth Ebony");
        builder.add(TMMBlocks.SMOOTH_EBONY_STAIRS, "Smooth Ebony Stairs");
        builder.add(TMMBlocks.SMOOTH_EBONY_SLAB, "Smooth Ebony Slab");
        builder.add(TMMBlocks.EBONY_PANEL, "Ebony Panel");
        builder.add(TMMBlocks.EBONY_CABINET, "Ebony Cabinet");
        builder.add(TMMBlocks.TRIMMED_EBONY_STAIRS, "Trimmed Ebony Stairs");
        builder.add(TMMBlocks.EBONY_BOOKSHELF, "Ebony Bookshelf");
        builder.add(TMMBlocks.OAK_BRANCH, "Oak Branch");
        builder.add(TMMBlocks.SPRUCE_BRANCH, "Spruce Branch");
        builder.add(TMMBlocks.BIRCH_BRANCH, "Birch Branch");
        builder.add(TMMBlocks.JUNGLE_BRANCH, "Jungle Branch");
        builder.add(TMMBlocks.ACACIA_BRANCH, "Acacia Branch");
        builder.add(TMMBlocks.DARK_OAK_BRANCH, "Dark Oak Branch");
        builder.add(TMMBlocks.MANGROVE_BRANCH, "Mangrove Branch");
        builder.add(TMMBlocks.CHERRY_BRANCH, "Cherry Branch");
        builder.add(TMMBlocks.BAMBOO_POLE, "Bamboo Pole");
        builder.add(TMMBlocks.CRIMSON_STIPE, "Crimson Stipe");
        builder.add(TMMBlocks.WARPED_STIPE, "Warped Stipe");
        builder.add(TMMBlocks.STRIPPED_OAK_BRANCH, "Stripped Oak Branch");
        builder.add(TMMBlocks.STRIPPED_SPRUCE_BRANCH, "Stripped Spruce Branch");
        builder.add(TMMBlocks.STRIPPED_BIRCH_BRANCH, "Stripped Birch Branch");
        builder.add(TMMBlocks.STRIPPED_JUNGLE_BRANCH, "Stripped Jungle Branch");
        builder.add(TMMBlocks.STRIPPED_ACACIA_BRANCH, "Stripped Acacia Branch");
        builder.add(TMMBlocks.STRIPPED_DARK_OAK_BRANCH, "Stripped Dark Oak Branch");
        builder.add(TMMBlocks.STRIPPED_MANGROVE_BRANCH, "Stripped Mangrove Branch");
        builder.add(TMMBlocks.STRIPPED_CHERRY_BRANCH, "Stripped Cherry Branch");
        builder.add(TMMBlocks.STRIPPED_BAMBOO_POLE, "Stripped Bamboo Pole");
        builder.add(TMMBlocks.STRIPPED_CRIMSON_STIPE, "Stripped Crimson Stipe");
        builder.add(TMMBlocks.STRIPPED_WARPED_STIPE, "Stripped Warped Stipe");
        builder.add(TMMBlocks.PANEL_STRIPES, "Panel Stripes");
        builder.add(TMMBlocks.TRIMMED_RAILING, "Trimmed Railing");
        builder.add(TMMBlocks.CARGO_BOX, "Cargo Box");
        builder.add(TMMBlocks.WHITE_LOUNGE_COUCH, "White Lounge Couch");
        builder.add(TMMBlocks.WHITE_TRIMMED_BED, "White Trimmed Bed");
        builder.add(TMMBlocks.RED_TRIMMED_BED, "Red Trimmed Bed");
        builder.add(TMMBlocks.WHITE_OTTOMAN, "White Ottoman");
        builder.add(TMMBlocks.BLUE_LOUNGE_COUCH, "Blue Lounge Couch");
        builder.add(TMMBlocks.GREEN_LOUNGE_COUCH, "Green Lounge Couch");
        builder.add(TMMBlocks.RED_LEATHER_COUCH, "Red Leather Couch");
        builder.add(TMMBlocks.BROWN_LEATHER_COUCH, "Brown Leather Couch");
        builder.add(TMMBlocks.BEIGE_LEATHER_COUCH, "Beige Leather Couch");
        builder.add(TMMBlocks.COFFEE_TABLE, "Coffee Table");
        builder.add(TMMBlocks.BAR_TABLE, "Bar Table");
        builder.add(TMMBlocks.BAR_STOOL, "Bar Stool");
        builder.add(TMMBlocks.GOLD_BAR, "Gold Bar");
        builder.add(TMMBlocks.GOLD_LEDGE, "Gold Ledge");
        builder.add(TMMBlocks.STAINLESS_STEEL_BAR, "Stainless Steel Bar");
        builder.add(TMMBlocks.TRIMMED_LANTERN, "Trimmed Lantern");
        builder.add(TMMBlocks.WALL_LAMP, "Wall Lamp");
        builder.add(TMMBlocks.NEON_PILLAR, "Neon Pillar");
        builder.add(TMMBlocks.NEON_TUBE, "Neon Tube");
        builder.add(TMMBlocks.STAINLESS_STEEL_SPRINKLER, "Stainless Steel Sprinkler");
        builder.add(TMMBlocks.GOLD_SPRINKLER, "Golden Sprinkler");
        builder.add(TMMBlocks.SMALL_BUTTON, "Small Button");
        builder.add(TMMBlocks.ELEVATOR_BUTTON, "Elevator Button");
        builder.add(TMMBlocks.GOLD_ORNAMENT, "Golden Ornament");
        builder.add(TMMBlocks.SMALL_GLASS_DOOR, "Small Glass Door");
        builder.add(TMMBlocks.SMALL_WOOD_DOOR, "Small Wood Door");
        builder.add(TMMBlocks.SMALL_TRAIN_DOOR, "Small Train Door");
        builder.add(TMMBlocks.NAVY_STEEL, "Navy Steel");
        builder.add(TMMBlocks.NAVY_STEEL_PANEL, "Navy Steel Panel");
        builder.add(TMMBlocks.NAVY_STEEL_TILES, "Navy Steel Tiles");
        builder.add(TMMBlocks.NAVY_STEEL_TILES_PANEL, "Navy Steel Tiles Panel");
        builder.add(TMMBlocks.SMOOTH_NAVY_STEEL, "Smooth Navy Steel");
        builder.add(TMMBlocks.SMOOTH_NAVY_STEEL_STAIRS, "Smooth Navy Steel stairs");
        builder.add(TMMBlocks.SMOOTH_NAVY_STEEL_SLAB, "Smooth Navy Steel slab");
        builder.add(TMMBlocks.SMOOTH_NAVY_STEEL_PANEL, "Smooth Navy Steel panel");
        builder.add(TMMBlocks.SMOOTH_NAVY_STEEL_WALL, "Smooth Navy Steel Wall");

        builder.add(TMMItems.KEY, "Key");
        builder.add(TMMItems.LOCKPICK, "Lockpick");
        builder.add(TMMItems.KNIFE, "Knife");
        builder.add(TMMItems.REVOLVER, "Revolver");
        builder.add(TMMItems.BODY_BAG, "Body Bag");
        builder.add(TMMItems.LETTER, "Letter");

        builder.add(TMMItems.LETTER.getTranslationKey() + ".instructions", "Instructions");
        builder.add("tip.letter.hitman.tooltip1", "Thank you for taking this job. Please eliminate the following targets:");
        builder.add("tip.letter.hitman.tooltip.target", "- %s");
        builder.add("tip.letter.hitman.tooltip2", "Please do so with the utmost discretion and do not get caught. Good luck.");
        builder.add("tip.letter.hitman.tooltip3", "");
        builder.add("tip.letter.hitman.tooltip4", "P.S.: Don't forget to use your instinct [Left Alt] and use the train's exterior to relocate.");

        builder.add(TMMItems.LETTER.getTranslationKey() + ".notes", "Notes");
        builder.add("tip.letter.detective.tooltip1", "Multiple homicides, several wealthy victims.");
        builder.add("tip.letter.detective.tooltip2", "Have to be linked... Serial killer? Assassin? Hitman?");
        builder.add("tip.letter.detective.tooltip3", "Potential next victims frequent travelers of the Harpy Express.");
        builder.add("tip.letter.detective.tooltip4", "Perfect situation to corner but need to keep targets safe.");

        builder.add(TMMItems.LETTER.getTranslationKey() + ".pamphlet", "Pamphlet");
        builder.add("tip.letter.pamphlet.name", "Dear %s, welcome aboard the Harpy Express!");
        builder.add("tip.letter.pamphlet.room", "Please find attached your ticket as well as the key for accessing");
        builder.add("tip.letter.pamphlet.room.grand_suite", "the Grand Suite");
        builder.add("tip.letter.pamphlet.room.cabin_suite", "your Cabin Suite");
        builder.add("tip.letter.pamphlet.room.twin_cabin", "your Twin Cabin");
        builder.add("tip.letter.pamphlet.tooltip1", "%s for your trip on the 1st of January 1923.");
        builder.add("tip.letter.pamphlet.tooltip2", "La Sirène wishes you a pleasant and safe voyage.");

        builder.add("itemGroup.trainmurdermystery.building", "TrainMurderMystery: Building Blocks");
        builder.add("itemGroup.trainmurdermystery.decoration", "TrainMurderMystery: Decoration & Functional");
        builder.add("itemGroup.trainmurdermystery.equipment", "TrainMurderMystery: Equipment");

        builder.add("container.cargo_box", "Cargo Box");
        builder.add("container.cabinet", "Cabinet");
        builder.add("subtitles.block.cargo_box.close", "Cargo Box closes");
        builder.add("subtitles.block.cargo_box.open", "Cargo Box opens");
        builder.add("subtitles.block.door.toggle", "Door operates");

        builder.add("tip.door.locked", "This door is locked and cannot be opened.");
        builder.add("tip.door.requires_key", "This door is locked and requires a key to be opened.");
        builder.add("tip.door.requires_different_key", "This door is locked and requires a different key to be opened.");
        builder.add("tip.door.jammed", "This door is jammed and cannot be opened at the moment!");

        builder.add("tip.cooldown", "On cooldown: %s");
        builder.add("tip.knife.tooltip1", "Right-click to use, hold for a second and get close to your victim!");
        builder.add("tip.knife.tooltip2", "After a kill, cannot be used for 3 minutes");
        builder.add("tip.knife.tooltip3", "Attack to knock back / push a player (no cooldown)");
        builder.add("tip.lockpick.tooltip1", "Use on any locked door to open it (no cooldown)");
        builder.add("tip.lockpick.tooltip2", "Sneak-use on a door to jam it for 1 minute (disables the lockpick for 5 minutes)");
        builder.add("tip.revolver.rounds", "%s/6 rounds left");
        builder.add("tip.revolver.tooltip1", "Right-click to use, point and shoot");
        builder.add("tip.revolver.tooltip2", "Can be used to shoot a door and open it permanently (only glass and wooden doors)");
        builder.add("tip.body_bag.tooltip1", "Use on a dead body to bag it up and remove it");

        builder.add("game.win.hitmen", "All targets were eliminated: The Hitmen win!");
        builder.add("game.win.passengers", "All hitmen were eliminated: The Passengers win!");

        builder.add("key.trainmurdermystery.instinct", "Instinct");
        builder.add("category.trainmurdermystery.keybinds", "Train Murder Mystery");
    }
}
